graph LR;

  subgraph WP2 [ WP2 Technology assessment, mapping and pooling];
     2.2.2(2.2.2 Resource catelogue)
     2.1.7(2.1.7 Storage needs document)
     2.1.8(2.1.8 Analysis needs document)
     2.1.9(2.1.9 Training needs document)
  end
  
  subgraph WP4 [ WP4 User support];
     4.1.1(4.1.1 Project specific assitance plan)
  end
  
  subgraph WP5 [ WP5];
    5.4.1(5.4.1 Work-pakage related publications portal)
  end
  
  subgraph WP7.1 [ WP7.1 - Identify potential users, use cases  from survey];
     7.1.2(7.1.2 NAIC use case development and demonstrators plan)
     7.1.1(7.1.1 Potential NAIC use-cases summary)
     2.2.2 -.-> 7.1.2
     7.1.2 -.-> 7.1.1  
     7.1.2 -.-> 4.1.1
     7.1.1 -.-> 5.4.1
  end
  
  subgraph WP7.2 [ WP7.2 - Use case 1: Climate community, Teleconnections];
      7.2.1(7.2.1 Climate community, Teleconnections summary)
      7.1.2 -.-> 7.2.1
      7.2.1 -.-> 7.1.1
  end
  
  subgraph WP7.3 [ WP7.3 Abstraction from experience, conclusions on<br> changes of collaboration model and use case development];
    7.3.1(7.3.1 Improvements list for collaboration model and use case development)
    7.3.1 -.-> 7.1.2        
  end
  
  subgraph WP7.4 [ WP7.4 Contribution to requirements of possible cloud infratructures];
    7.4.1(7.4.1 Recomendations for infrastructure requirments)
    7.1.1 -.-> 7.4.1
    7.4.1 -.->2.1.7
    7.4.1 -.->2.1.8
    7.4.1 -.->2.1.9
  end
    
  subgraph WP7.5 [ WP7.5 Use case 2: Barentswatch, wave modeling];
      7.5.1(7.5.1 Barentswatch, wave modeling summary)
      7.1.2 -.-> 7.5.1
      7.5.1 -.-> 7.1.1
  end
  
 subgraph WP7.6 [ WP7.6 Pseudo-hamiltonian neural networks];
    7.6.1(7.6.1 Pseudo-hamiltonian neural networks summary)
    7.1.2 -.-> 7.6.1
    7.6.1 -.-> 7.1.1
  end

  subgraph WP7.7 [ WP7.7 Use case 4: Federated learning in health ];
    7.7.1(7.7.1 Federated learning in health summary)
    7.1.2 -.-> 7.7.1
    7.7.1 -.-> 7.1.1
    
  end

  subgraph WP7.UC2 [ UC2: PEM Electrolyzer PINN Optimizer];
    UC2(UC2 PEM Electrolyzer Digital Twin)
    7.1.2 -.-> UC2
    UC2 -.-> 7.1.1
  end

  subgraph WP7.UC6 [ UC6: Multi-Modal Optimization];
    UC6(UC6 Scalable Hybrid GA - Johannsen et al.)
    7.1.2 -.-> UC6
    UC6 -.-> 7.1.1
  end

  subgraph WP7.UC7 [ UC7: Latent Representation of PDE Solutions];
    UC7(UC7 Latent Representation of PDE Solutions)
    7.1.2 -.-> UC7
    UC7 -.-> 7.1.1
  end

  subgraph WP7.10 [ 7.10 Summary of completed demonstrators];
    7.10.1(7.10 Summary of completed demonstrators)
    7.1.1 -.-> 7.10.1
  end

  subgraph WP7.11 [ 7.11 Summary of contributions for training and documentation];
    7.11.1(7.11 Training and documentation contributions)
    7.1.1 -.-> 7.11.1
  end


click 7.1.2 "https://gitlab.sigma2.no/naic/wp7/d7.1-identify-use-cases-from-the-survey-and-partner-networks/-/issues/1"
click 7.1.1 "https://gitlab.sigma2.no/naic/wp7/d7.1-identify-use-cases-from-the-survey-and-partner-networks/-/issues/2"
click 7.2.1 "https://gitlab.sigma2.no/naic/wp7/d7.2-Use-case1/-/issues/1"
click 7.3.1 "https://gitlab.sigma2.no/naic/wp7/d7.3-abstraction-from-experience-conclusions-on-changes-of-collaboration-model-and-use-case-development/-/issues/1"
click 7.4.1 "https://gitlab.sigma2.no/naic/wp7/contribution-to-requirements-of-possible-cloud-infratructures/-/issues/1"
click 7.5.1 "https://gitlab.sigma2.no/naic/wp7/d7.5-usecase2/-/issues/1"
click 7.6.1 "https://gitlab.sigma2.no/naic/wp7/d7.6-use-case-3/-/issues/1"
click 7.7.1 "https://gitlab.sigma2.no/naic/wp7/d7.7-usecase-4/-/issues/1"
click UC2 "https://gitlab.sigma2.no/naic/wp7/uc2-pem-electrolyzer-pinn-optimizer"
click UC6 "https://gitlab.sigma2.no/naic/wp7/multi-modal-optimization"
click UC7 "https://gitlab.sigma2.no/naic/wp7/latent-representation-of-pde-solutions"
click 7.10.1 "https://gitlab.sigma2.no/naic/wp7/d7.10-collaboration-model-and-use-case-development-procudurement"
click 7.11.1 "https://gitlab.sigma2.no/naic/wp7/d7.11-summary-of-completed-demonstrators"

click 2.1.7 "https://gitlab.sigma2.no/naic/wp2/map-user-needs/-/issues/9"
click 2.1.8 "https://gitlab.sigma2.no/naic/wp2/map-user-needs/-/issues/10"
click 2.1.9 "https://gitlab.sigma2.no/naic/wp2/map-user-needs/-/issues/12"
click 2.2.2 "https://gitlab.sigma2.no/naic/wp2/document-existing-resources/-/issues/6"

click 4.1.1 "https://gitlab.sigma2.no/naic/wp4/wp4.1-project-specific-assistance/-/issues/1"
click 5.4.1 "https://gitlab.sigma2.no/naic/wp5/naic-work-pakage-publication-coordination/-/issues/1"

 classDef c1 fill:#eedddd,stroke:#000000;
 classDef c2 fill:#ddeedd,stroke:#000000;
 classDef c3 fill:#ddddee,stroke:#000000;
 classDef c4 fill:#ccdddd,stroke:#000000;
 classDef c5 fill:#ddccdd,stroke:#000000;
 classDef c6 fill:#ddddcc,stroke:#000000;
 classDef c7 fill:#ddcccc,stroke:#000000;
 classDef c8 fill:#ffddcc,stroke:#000000;
 classDef done fill:#555555,stroke:#ffffff,color:#ffffff;

 class WP7.1 c7;
 class WP7.2 c7;
 class WP7.3 c7;
 class WP7.4 c7;
 class WP7.5 c7;
 class WP7.6 c7;
 class WP7.7 c7;
 class WP7.UC2 c7;
 class WP7.UC6 c7;
 class WP7.UC7 c7;
 class WP7.10 c7;
 class WP7.11 c7;

 class WP1 c1;
 class WP2 c2;
 class WP3 c3;
 class WP4 c4;
 class WP5 c5;
 class WP6 c6;
 class WP7 c7;
 class WP8 c8;

 

 

