#!/bin/bash
# Create hedgdocs idirectly
# sabryr 18-08-2022

DOCUMENT_CONTROL=$1
TEMPLATESNIPPET=$2
ISSUEID=$3
GITLAB_TOKEN=$4
CI_PROJECT_ID=$5
TEMP_FILE="HEDGEDOC_TMP.md"
BRANCH=$6
GTILABFILE=$7

#NEWFILEPATH=$1
#CONTENT=$2
#ISSUEID=$3
#GITLAB_TOKEN=$4
#PROJECT_ID=$5
#
HEDGEDOCURL="https://md.sigma2.no/" 
HEDGEDOCDBIN="./scripts/bin/hedgedoc" #This is hardcoded to executable HEDGEDOCDBIN
LOG_FILE="script.log"

function logme {
   echo "$@" >> $LOG_FILE
}


function encode() { 
     input=$1
     output=$(echo $input | sed -e 's/\//%2F/g');
     echo $output 
}

function genratehedgedoc () {
      logme $(echo "$LINENO Should create Hedgedoc for "$TEMP_FILE)
      # Get the document control infomation and template content and 
      # Create a hedgedoc
      HEDGE_URL="bash $HEDGEDOCDBIN import $TEMP_FILE"
      #Get the created Hedgedoc id
      result=$(eval $HEDGE_URL | tail -n 1)
      echo "result $result"
      logme $(echo "$LINENO hedgedoc resutl $result")
      # Fabricate the Hedgedoc URL using the id from cmd client
      # Updadate the issue with the URL
      local result_url="https://md.sigma2.no/${result}"
      updateissue ${ISSUEID} "%28Step%202%20of%205%29%20Link%20to%20the%20hedgedoc%20${result_url}"
      # Create a placeholder for Hedgedoc so it can be pulled later
      createplaceholder ${result_url} ${BRANCH} ${GTILABFILE} ${ISSUEID}
      #TODO see if previous step was successfull
      request_merge ${BRANCH} ${ISSUEID} 
}

function updateissue () {
  logme $(echo "$LINENO Createfromapi call from $4 ")
  if [ "$#" -ge 2 ]
  then
     local CURLARG="--request POST"
     local TYPE="issues/$1/"
     local message="$2" 
     local ARGUMENTS="notes?body=$message"

     #local ARGUMENTS="notes?body=Link%20to%20the%20hedgedoc%20https://md.sigma2.no/"${hedgedoc_id}
     CURL_URL="curl ${CURLARG} --header \"PRIVATE-TOKEN: ${GITLAB_TOKEN}\" \"${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/${TYPE}${ARGUMENTS}\""
     logme $(echo "$LINENO $CURL_URL")
     echo " Update issue " $CURL_URL
     API_RESULT=$(eval $CURL_URL)
     echo "$API_RESULT"
  fi
}


function createplaceholder (){
  logme $(echo "$LINENO Createfromapi call from $4 ")
  if [ "$#" -ge 3 ]
  then
     local hedgedoc_url="$1"
     local TYPE="/repository/files/"
     local branch="$2"
     local filename=$(encode $3)
     local issueid=$4
     local contant="Please do not edit this file. This file will be automatically updated with the contant of\r\n\r\n##HEDGEDOCSYNCFILE##=$hedgedoc_url\r\n\r\nISSUEID=$issueid" 
     local CURLARG="--request POST --data '{\"branch\": \"$branch\", \"author_name\": \"FitSM-bot\",\"content\": \"$contant\", \"commit_message\": \"Place holder docuement created[WIP]\"}'"

     CURL_URL="curl ${CURLARG}  --header \"Content-Type: application/json\" --header \"PRIVATE-TOKEN: ${GITLAB_TOKEN}\" \"${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/${TYPE}${filename}\""
     logme $(echo "$LINENO $CURL_URL")
     echo " createplaceholder " $CURL_URL
     API_RESULT=$(eval $CURL_URL)
     echo "$API_RESULT"
  fi
}

function request_merge (){
  logme $(echo "$LINENO Ask the user to create a merge request to confirm editing finished")
  if [ "$#" -ge 1 ]
  then
    local sourcebranch="$1"
    local taregtbranch="master"
    local issueid="$2"
    local CURLARG="--request POST"
    local TYPE="merge_requests"
    #local arguments="?description=Refer%20issue%20%23${issueid}%20for%20details%20Closes%20%23${issueid}"
    #arguments="${arguments}&remove_source_branch=true&target_branch=${taregtbranch}&source_branch=${sourcebranch}"
    #arguments="${arguments}&title=Placeholder%20for%20hedgedoc%5BWIP%5D"
    #arguments="${arguments}&remove_source_branch"
    CURL_URL="${CI_PROJECT_URL}/-/merge_requests/new?merge_request%5Bsource_branch%5D=${BRANCH}"
    MESSAGE="%28Step%203%20of%205%29%20A%20When%20finish%20editing%20the%20Hedgedoc%2C%20create%20a%20merge%20request%20by%20using%20the%20URL%20to%20sync%20${CURL_URL}"
    updateissue  ${ISSUEID} "${MESSAGE}"
  fi
}
function decode() { 
     : "${*//+/ }"; 
     echo -e "${_//%/\\x}";
}

if [[ ! -z "$DOCUMENT_CONTROL" ]]
then
     decode "$DOCUMENT_CONTROL" >> "$TEMP_FILE"
     genratehedgedoc
fi
